

version: '3.9'

services:
  api-agent:
    build: ./agents/api_agent_service
    ports:
      - "8001:8001"

  retriever-agent:
    build: ./agents/retriever_agent_service
    ports:
      - "8002:8002"

  scraping-agent:
    build: ./agents/scraping_agent_service
    ports:
      - "8003:8003"

  llm-agent:
    build: ./agents/llm_agent_service
    ports:
      - "8004:8004"

  voice-agent:
    build: ./agents/voice_agent
    ports:
      - "8005:8005"
    depends_on:
      - llm-agent

  orchestrator:
    build: ./orchestrator/orchestrator_service
    ports:
      - "8000:8000"
    depends_on:
      - api-agent
      - retriever-agent
      - scraping-agent
      - llm-agent
      - voice-agent

  streamlit-app:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - orchestrator
